[package]
name = "common-arm"
description = "Common embedded code for the boards"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { workspace = true }
defmt = { workspace = true }
defmt-rtt = { workspace = true }
heapless = "0.7.16"
derive_more = "0.99.17"
messages-prost = { workspace = true }
nb = { workspace = true }
panic-probe = { workspace = true }
embassy-time = { version = "0.4.0", features = [
	"defmt",
	"defmt-timestamp-uptime",
	"tick-hz-32_768",
] }
embassy-embedded-hal = { version = "0.3.0" }
embedded-hal-async = { version = "1.0" }
embedded-nal-async = "0.8.0"
embedded-io-async = { version = "0.6.1" }
embedded-hal = "1.0.0"

[[test]]
name = "example"
harness = false

[lib]
name = "common_arm"
harness = false
