[package]
name = "mavlink-ground-station-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
mavlink = { workspace = true, features = ["std"] }
tokio = { version = "1.49.0", features = ["full"] }
serial2-tokio = "0.1.19"
socket2 = { version = "0.6.1" }
