[package]
name = "sergw"
edition = "2021"
version.workspace = true
authors.workspace = true
publish.workspace = true
license.workspace = true
license-file.workspace = true

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
ctrlc = "3.4"
serialport = "4"
