[target.thumbv7em-none-eabihf]
# nRF52840 DK
runner = "qemu-system-aarch64.exe -machine mps2-an500"
rustflags = [
  "-C", "link-arg=-Tlink.x",  # required by cortex-m-rt
  "-C", "link-arg=-Tdefmt.x", # defmt logs
]

[build]
# cross compilation target = ARM Cortex-M4F
target = "thumbv7em-none-eabihf"