[package]
name = "uor-proc-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.1"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "2.0.15", features = ["full", "visit", "parsing"] }
