on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "boards/argus/**"
      - "common/**" # because argus has some dependencies on common
  workflow_dispatch:
name: Build Verification

jobs:
  checks:
    uses: ./.github/workflows/build.yml
    with:
      crate-name: argus
      crate-path: boards/argus
      # TODO: Checks for the other types of board (might benefit from use of matrices)
      default-features: temperature

  build_pressure:
    name: Build with Pressure Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - name: "Build with Pressure Feature"
        run: cargo build --release --features pressure
        working-directory: boards/argus

  build_temperature:
    name: Build with Temperature Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - name: "Build with Temperature Feature"
        run: cargo build --release --features temperature
        working-directory: boards/argus

  build_strain:
    name: Build with Strain Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - name: "Build with Strain Feature"
        run: cargo build --release --features strain
        working-directory: boards/argus
