# SHOULD DO: dedupe these and clean them up
on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/argus/**'
      - 'boards/argus/**'
      - 'common/**' # because argus has some dependencies on common
  workflow_dispatch:
name: Build Verification

jobs:
  formatting:
    name: Check for Formatting/Linting/Semantic Issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - name: Install Formatting Dependencies
        run: |
          cargo install cargo-sort
          rustup component add rustfmt

      - name: Check Formatting
        run: cargo fmt -- --check

      - name: Check Cargo.toml Sorting
        run: cargo sort --check

      - name: Check for Clippy Warnings
        run: cargo clippy --all-targets --all-features

  build_pressure:
    name: Build with Pressure Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - name: "Build with Pressure Feature"
        run: cargo build --release --features pressure
        working-directory: boards/argus

  build_temperature:
    name: Build with Temperature Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - name: "Build with Temperature Feature"
        run: cargo build --release --features temperature
        working-directory: boards/argus

  build_strain:
    name: Build with Strain Feature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - name: "Build with Strain Feature"
        run: cargo build --release --features strain
        working-directory: boards/argus

  test:
    name: Run Host Tests
    runs-on: ubuntu-latest
    env:
      RUST_MIN_STACK: 8388608
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - uses: actions-rs/cargo@v1
        name: "Run Host Tests"
        with:
          command: make
          args: test-host