on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "boards/phoenix/**"
      - "common/**" # because phoenix has some dependencies on common
  workflow_dispatch:
name: Build Verification

jobs:
  checks:
    uses: ./.github/workflow/build.yml@5b631423b2b4a90ee887956bf9f6a541edea234a
    with:
      crate-name: phoenix
      crate-path: boards/phoenix
      default-features: music

  build:
    name: Build Phoenix (All Features)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust Environment (Cached)
        uses: ./.github/actions/common/setup-rust-environment/

      - name: Build
        run: cargo build --release --features pressure
        working-directory: boards/phoenix
